### PR TITLE
cis: switch to Github actions

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
@rassouly @MVillius 
Are you using the nightly conda packages ? Now that all dependencies have clean wheels or exist on conda-forge maintaining or own conda packages does not seem that relevant anymore. Furthermore since we do not have recent release I believe everybody run from github anyway, so I would be in favor of not building those.

If you agree, I will go ahead with this and the similar PR on exopy-pulses.

**Comment by rassouly** [comment]
We are using exopy straight from git with the setup.py file i.e. we install it using `pip install -e .`. So you can go ahead with this change.

**Comment by MVillius** [comment]
Honestly I have no idea of what you are talking about Madar, but since we are doing the same type of install as Reouven, I guess we are fine!

**Comment by MatthieuDartiailh** [comment]
Then, I will go even further and remove the tools to build conda packages (we could fish them out later from the history if a need appears). Thanks to both of you. @rassouly once this and its counterpart in exopy_pulses land, please rebase https://github.com/Exopy/exopy_pulses/pull/27 to get a clean ci run.

**Pull request merged**
